Repository AY1920S1-CS2103T-T09-3/main, pull requests merged in 2019-10, with the labels that each got.

#48 Update developer guide
  docs/DeveloperGuide.adoc
Labels: documentation

#52 Updates readme file
  README.adoc
Labels: documentation

#53 Updates AboutUs.
  docs/AboutUs.adoc
Labels: documentation

#65 HOTFIX: Caret no longer fly to end of CommandBox on edit.
  src/main/java/seedu/address/ui/CommandBox.java
Labels: bug

#70 GUI enhancement.
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/ui/AutoCompleteOverlay.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TabBar.java
  src/main/resources/images/appointment.png
  src/main/resources/images/doctor.png
  src/main/resources/images/patient.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EventListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/TabBar.fxml
Labels: enhancement

#69 Update developer guide
  docs/DeveloperGuide.adoc
Labels: documentation

#83 Implements History & Moved AutoCompleter out of Logic.
  docs/team/carbongrid.adoc
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/AutoComplete.java
  src/main/java/seedu/address/ui/AutoCompleteOverlay.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/OmniPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/TabBar.java
  src/main/java/seedu/address/ui/autocomplete/AutoCompleter.java
  src/main/java/seedu/address/ui/autocomplete/Trie.java
  src/main/java/seedu/address/ui/autocomplete/TrieNode.java
  src/main/java/seedu/address/ui/commandboxhistory/CommandBoxHistory.java
  src/test/java/seedu/address/MainAppTest.java
  src/test/java/seedu/address/ui/OmniPanelStub.java
  src/test/java/seedu/address/ui/autocomplete/AutoCompleterTest.java
Labels: bug, enhancement

#89 Updated DeveloperGuide.adoc, carbongrid.adoc & Gradle wrapper.
  docs/DeveloperGuide.adoc
  docs/diagrams/AutoCompleteSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AutoCompleteSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/team/carbongrid.adoc
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: documentation

#94 Updates DG and removes GUI (UC11)
  docs/DeveloperGuide.adoc
Labels: documentation

#97 Removes navbar of seedu.
  build.gradle
Labels: documentation

#112 fixes bugs in Appointment commands and adds more test cases
  src/main/java/seedu/address/logic/commands/AckAppCommand.java
  src/main/java/seedu/address/logic/commands/AddAppCommand.java
  src/main/java/seedu/address/logic/commands/AppointmentsCommand.java
  src/main/java/seedu/address/logic/commands/CancelAppCommand.java
  src/main/java/seedu/address/logic/commands/MissAppCommand.java
  src/main/java/seedu/address/logic/commands/SettleAppCommand.java
  src/main/java/seedu/address/logic/commands/common/CommandResult.java
  src/main/java/seedu/address/logic/parser/AckAppCommandParser.java
  src/main/java/seedu/address/logic/parser/AddAppCommandParser.java
  src/main/java/seedu/address/logic/parser/AppointmentsCommandParser.java
  src/main/java/seedu/address/logic/parser/CancelAppCommandParser.java
  src/main/java/seedu/address/logic/parser/ChangeAppCommandTimingParser.java
  src/main/java/seedu/address/logic/parser/MissAppCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SettleAppCommandParser.java
  src/main/java/seedu/address/model/events/Event.java
  src/main/java/seedu/address/model/events/parameters/Timing.java
  src/main/java/seedu/address/model/events/predicates/EventContainsApprovedStatusPredicate.java
  src/main/java/seedu/address/model/events/predicates/EventContainsKeywordOrRecentlyAcknowledgedPredicate.java
  src/test/java/seedu/address/logic/commands/AckAppCommandTest.java
  src/test/java/seedu/address/logic/commands/AddAppCommandTest.java
  src/test/java/seedu/address/logic/commands/AppointmentsCommandTest.java
  src/test/java/seedu/address/logic/commands/CancelAppCommandTest.java
  src/test/java/seedu/address/logic/commands/ChangeAppCommandTest.java
  src/test/java/seedu/address/logic/commands/MissAppCommandTest.java
  src/test/java/seedu/address/logic/commands/SettleAppCommandTest.java
  src/test/java/seedu/address/logic/parser/AddAppCommandParserTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High

#114 Implements basic eager evaluation
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SetFocusOnTabCommand.java
  src/main/java/seedu/address/logic/commands/appointments/AppointmentsCommand.java
  src/main/java/seedu/address/logic/commands/patients/ListPatientCommand.java
  src/main/java/seedu/address/logic/commands/staff/ListStaffCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/person/predicates/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SamplePersonDataUtil.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: help wanted

#140 More UI Enhancements.
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TabBar.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/queue/QueueListCard.fxml
  src/main/resources/view/queue/QueueListPanel.fxml
  src/main/resources/view/queue/RoomListCard.fxml
Labels: enhancement
